repos:
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
    #
    # Go Build
    #
    -   id: go-build-repo-mod
        always_run: true
        verbose: true

    #
    # Go Test
    #
    -   id: go-test-repo-mod
        verbose: true

    #
    # Go Vet
    #
    -   id: go-vet-repo-mod
        always_run: true
        verbose: true
    #
    # StaticCheck
    #
    -   id: go-staticcheck-repo-mod
        always_run: true
        verbose: true
    #
    # Go Mod Tidy
    #
    -   id: go-mod-tidy-repo
        always_run: true
        verbose: true
    #
    # Formatters
    #
    -   id: go-fmt-repo
        always_run: true
        verbose: true
    -   id: go-imports-repo
        always_run: true
        verbose: true
    #
    # Custom Hooks
    #
    -   name: go-errcheck-repo
        id: my-cmd-repo
        args: [ "errcheck" ]
        always_run: true
        verbose: true
    -   name: go-make-manifests
        id: my-cmd-repo
        args: [ "make", "all" ]
        always_run: true
        verbose: true
