{{ range .Values.nodeCIDRAllocations }}
apiVersion: networking.statcan.gc.ca/v1alpha1
kind: NodeCIDRAllocation
metadata:
  name: {{ .name }}
  labels: {{- include "cidr-allocator.labels" $ | nindent 4 }}
spec:
  nodeSelector: {{ toYaml .nodeSelector | nindent 4 }}
  addressPools: {{ toYaml .addressPools | nindent 4 }}
{{ end }}
